import { authOptions } from '@/lib/auth'
import AppBar from './appBar'
import './globals.css'
import { getServerSession } from 'next-auth'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)
  console.log("sess",session);
  return (
    <html lang="en">
      <body>
          <AppBar session={session} />
          <div className={"  h-screen "}>{children}</div>
      </body>
    </html>
  )
}
